export { Navbar } from "./Navbar/Navbar";
export { Hero } from "./Hero/Hero";
export { HeroAnimation } from "./Hero/HeroAnimation";
export { About } from "./About/About";
export { Qualification } from "./Qualification/Qualification";
export { Skills } from "./Skills/Skills";
export { Projects } from "./Projects/Projects";
export { Contact } from "./Contact/Contact";
export { Footer } from "./Footer/Footer";
